### ISSUE TITLE
bad optimization

### ISSUE THREAD

**Issue by mlodyskiny** [MaddyOff/ue4-canvas-gui#4]
when menu is open my fps drop from 300-400 to 20-30, i just have a window with no content

**Comment by MaddyOff** [comment]
Hey. I think you made something wrong.
Or idk, maybe some things are updated. I didn't check source for long time.

ср, 1 мар. 2023 г. в 00:11, parkie ***@***.***>:

**Comment by mlodyskiny** [comment]
it was my source issue, everything is fine now, thank you for making this lib <333

**Comment by MaddyOff** [comment]
Good! :)
With which game you are working?

Чт, 2 марта 2023 г. в 02:22, parkie ***@***.***>:

**Comment by mlodyskiny** [comment]
im making a cheat for old fortnite versions, currently 7.40 and 10.40. engine rendering is good af for fps and looks a lot better than imgui
